### ISSUE TITLE
Autofac not resolving IEntityDeleteHandler

### ISSUE THREAD

**Issue by spencer-biri-vizient** [dalenewman/Transformalize#30]
When trying to set deletes to true for an entity, I get the following error:
```shell
Unhandled Exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating ?:Transformalize.Contracts.IProcessController. ---> Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'horizon-replicationvw_cds_rdw_mbr_acct_grp_sys (Transformalize.Contracts.IEntityDeleteHandler)' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveNamed[TService](IComponentContext context, String serviceName, IEnumerable`1 parameters)
   at Transformalize.Ioc.Autofac.Modules.ProcessControlModule.<Load>b__3_0(IComponentContext ctx)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Transformalize.Command.NowScheduler.Start()
   at Transformalize.Command.Program.Main(String[] args)
```

**Comment by dalenewman** [comment]
@Cendeu TBH I'm not sure the delete feature was every really totally implemented.  I know I may of had it working to some extent for SQL Server 🤔  I am wondering what output provider you're using?  Thanks!
